export const OBJETS_PREDEFINIS = [
  // ─── SALON / SÉJOUR ───
  { nom: 'Canapé 1 place', volume: 0.7 },
  { nom: 'Canapé 2 places', volume: 1.0 },
  { nom: 'Canapé 3 places', volume: 1.5 },
  { nom: 'Canapé 4 places', volume: 2.0 },
  { nom: "Canapé d'angle", volume: 2.5 },
  { nom: 'Canapé panoramique', volume: 3.0 },
  { nom: 'Canapé convertible', volume: 2.0 },
  { nom: 'Canapé modulable (module)', volume: 0.9 },
  { nom: 'Banquette', volume: 1.2 },
  { nom: 'Méridienne', volume: 1.2 },
  { nom: 'Fauteuil', volume: 0.8 },
  { nom: 'Fauteuil relax / inclinable', volume: 1.0 },
  { nom: 'Fauteuil suspendu', volume: 0.9 },
  { nom: 'Fauteuil crapaud', volume: 0.7 },
  { nom: 'Fauteuil club', volume: 0.9 },
  { nom: 'Rocking-chair', volume: 0.8 },
  { nom: 'Chauffeuse', volume: 0.6 },
  { nom: 'Pouf', volume: 0.3 },
  { nom: 'Pouf géant', volume: 0.6 },
  { nom: 'Repose-pieds', volume: 0.2 },
  { nom: 'Table basse', volume: 0.5 },
  { nom: 'Table basse relevable', volume: 0.6 },
  { nom: 'Table gigogne (lot)', volume: 0.4 },
  { nom: 'Bout de canapé', volume: 0.2 },
  { nom: 'Meuble TV', volume: 0.8 },
  { nom: 'Meuble TV mural', volume: 1.2 },
  { nom: 'Télévision', volume: 0.3 },
  { nom: 'Télévision grand format (65"+)', volume: 0.5 },
  { nom: 'Support TV sur pied', volume: 0.3 },
  { nom: 'Bibliothèque', volume: 1.5 },
  { nom: "Bibliothèque d'angle", volume: 1.8 },
  { nom: 'Étagère', volume: 0.8 },
  { nom: 'Étagère murale', volume: 0.2 },
  { nom: 'Étagère cube / casier', volume: 0.6 },
  { nom: 'Vitrine / Vaisselier', volume: 1.8 },
  { nom: 'Buffet / Enfilade', volume: 1.5 },
  { nom: 'Bahut', volume: 1.4 },
  { nom: "Console d'entrée", volume: 0.6 },
  { nom: 'Meuble à chaussures', volume: 0.5 },
  { nom: 'Chaîne hi-fi / Enceintes', volume: 0.3 },
  { nom: 'Tapis (petit)', volume: 0.2 },
  { nom: 'Tapis (moyen)', volume: 0.35 },
  { nom: 'Tapis (grand)', volume: 0.5 },
  { nom: 'Lampadaire', volume: 0.3 },
  { nom: 'Lampe de table', volume: 0.1 },
  { nom: 'Horloge sur pied', volume: 0.6 },
  { nom: 'Paravent', volume: 0.3 },
  { nom: 'Porte-manteau sur pied', volume: 0.3 },
  { nom: "Cheminée d'appoint / Poêle", volume: 0.5 },
  { nom: 'Guéridon', volume: 0.3 },
  { nom: 'Sellette / Colonne déco', volume: 0.2 },
  { nom: 'Meuble bar', volume: 1.0 },
  { nom: "Meuble d'entrée / Vestiaire", volume: 0.8 },
  { nom: 'Banc de rangement / Coffre', volume: 0.5 },
  { nom: 'Portemanteau mural', volume: 0.1 },
  { nom: 'Portemanteau perroquet', volume: 0.3 },
  { nom: 'Porte-parapluie', volume: 0.05 },
  { nom: 'Porte-revues', volume: 0.05 },
  { nom: 'Meuble hi-fi / à vinyles', volume: 0.6 },
  { nom: 'Lustre', volume: 0.2 },
  { nom: 'Applique murale', volume: 0.05 },
  { nom: 'Grand miroir mural', volume: 0.2 },
  { nom: 'Tenture / Tapisserie murale', volume: 0.1 },
  { nom: 'Arbre de Noël (artificiel)', volume: 0.3 },

  // ─── SALLE À MANGER ───
  { nom: 'Table à manger (2 personnes)', volume: 0.8 },
  { nom: 'Table à manger (4 personnes)', volume: 1.2 },
  { nom: 'Table à manger (6 personnes)', volume: 1.8 },
  { nom: 'Table à manger (8 personnes)', volume: 2.5 },
  { nom: 'Table à manger (10+ personnes)', volume: 3.0 },
  { nom: 'Table extensible', volume: 1.5 },
  { nom: 'Table ronde', volume: 1.3 },
  { nom: 'Chaise', volume: 0.3 },
  { nom: 'Chaise pliante', volume: 0.15 },
  { nom: 'Tabouret', volume: 0.2 },
  { nom: 'Tabouret de bar', volume: 0.3 },
  { nom: 'Banc', volume: 0.5 },
  { nom: 'Desserte / Chariot', volume: 0.6 },
  { nom: 'Bar / Comptoir', volume: 1.2 },

  // ─── CHAMBRE ───
  { nom: 'Lit simple', volume: 1.5 },
  { nom: 'Lit double', volume: 2.5 },
  { nom: 'Lit queen size', volume: 2.7 },
  { nom: 'Lit king size', volume: 3.0 },
  { nom: 'Lit superposé', volume: 3.0 },
  { nom: 'Lit mezzanine', volume: 3.0 },
  { nom: 'Lit escamotable', volume: 2.0 },
  { nom: 'Lit coffre', volume: 2.7 },
  { nom: 'Lit bébé', volume: 1.0 },
  { nom: "Lit d'appoint / Clic-clac", volume: 1.5 },
  { nom: 'Lit gigogne', volume: 2.0 },
  { nom: 'Sommier simple', volume: 0.6 },
  { nom: 'Sommier double', volume: 1.0 },
  { nom: 'Sommier à lattes', volume: 0.5 },
  { nom: 'Matelas simple', volume: 0.8 },
  { nom: 'Matelas double', volume: 1.2 },
  { nom: 'Matelas queen size', volume: 1.35 },
  { nom: 'Matelas king size', volume: 1.5 },
  { nom: 'Matelas bébé', volume: 0.3 },
  { nom: 'Surmatelas', volume: 0.3 },
  { nom: 'Tête de lit', volume: 0.5 },
  { nom: 'Armoire 2 portes', volume: 2.5 },
  { nom: 'Armoire 3 portes', volume: 3.5 },
  { nom: 'Armoire 4 portes', volume: 4.5 },
  { nom: 'Armoire penderie', volume: 3.0 },
  { nom: 'Dressing / Penderie', volume: 3.0 },
  { nom: "Dressing d'angle", volume: 3.5 },
  { nom: 'Commode', volume: 1.0 },
  { nom: 'Chiffonnier', volume: 0.8 },
  { nom: 'Semainier', volume: 0.9 },
  { nom: 'Table de chevet', volume: 0.3 },
  { nom: 'Coiffeuse', volume: 0.8 },
  { nom: 'Miroir', volume: 0.3 },
  { nom: 'Miroir sur pied (psyché)', volume: 0.5 },
  { nom: 'Banc de lit', volume: 0.4 },
  { nom: 'Table à langer', volume: 0.5 },
  { nom: 'Bureau enfant', volume: 0.8 },

  // ─── BUREAU ───
  { nom: 'Bureau', volume: 1.2 },
  { nom: "Bureau d'angle", volume: 1.8 },
  { nom: 'Bureau assis-debout', volume: 1.5 },
  { nom: 'Secrétaire', volume: 1.0 },
  { nom: 'Chaise de bureau', volume: 0.5 },
  { nom: 'Fauteuil de direction', volume: 0.7 },
  { nom: 'Caisson / Meuble de rangement', volume: 0.5 },
  { nom: 'Armoire de bureau / Classeur', volume: 1.2 },
  { nom: 'Bibliothèque de bureau', volume: 1.5 },
  { nom: 'Coffre-fort', volume: 0.3 },
  { nom: 'Meuble à tiroirs (plan)', volume: 0.6 },

  // ─── CUISINE ───
  { nom: 'Réfrigérateur', volume: 1.2 },
  { nom: 'Réfrigérateur américain', volume: 2.0 },
  { nom: 'Réfrigérateur encastrable', volume: 1.0 },
  { nom: 'Mini-réfrigérateur', volume: 0.4 },
  { nom: 'Congélateur armoire', volume: 1.2 },
  { nom: 'Congélateur coffre', volume: 1.0 },
  { nom: 'Lave-vaisselle', volume: 0.8 },
  { nom: 'Four', volume: 0.5 },
  { nom: 'Four encastrable', volume: 0.4 },
  { nom: 'Cuisinière / Gazinière', volume: 0.8 },
  { nom: 'Piano de cuisson', volume: 1.2 },
  { nom: 'Plaque de cuisson', volume: 0.15 },
  { nom: 'Micro-ondes', volume: 0.2 },
  { nom: 'Hotte aspirante', volume: 0.3 },
  { nom: 'Table de cuisine', volume: 0.8 },
  { nom: 'Meuble de cuisine (élément haut)', volume: 0.5 },
  { nom: 'Meuble de cuisine (élément bas)', volume: 0.8 },
  { nom: 'Colonne de cuisine', volume: 1.0 },
  { nom: 'Îlot central', volume: 1.5 },
  { nom: 'Desserte de cuisine', volume: 0.5 },
  { nom: 'Cave à vin', volume: 0.8 },
  { nom: 'Robot de cuisine (grand)', volume: 0.2 },
  { nom: 'Garde-manger', volume: 1.0 },
  { nom: 'Machine à pain', volume: 0.05 },
  { nom: 'Fontaine à eau', volume: 0.3 },
  { nom: 'Distributeur de boissons', volume: 0.2 },
  { nom: 'Chariot de service', volume: 0.4 },

  // ─── CHAUFFAGE / CLIMATISATION / CONFORT ───
  { nom: 'Radiateur électrique', volume: 0.2 },
  { nom: "Radiateur bain d'huile", volume: 0.15 },
  { nom: "Chauffage d'appoint", volume: 0.1 },
  { nom: 'Climatiseur mobile', volume: 0.3 },
  { nom: 'Ventilateur sur pied', volume: 0.2 },
  { nom: 'Ventilateur colonne', volume: 0.15 },
  { nom: "Purificateur d'air", volume: 0.1 },
  { nom: 'Déshumidificateur', volume: 0.1 },
  { nom: 'Humidificateur', volume: 0.05 },
  { nom: 'Chauffe-eau / Ballon (déposé)', volume: 0.5 },
  { nom: "Adoucisseur d'eau", volume: 0.3 },

  // ─── BUANDERIE / SALLE DE BAIN ───
  { nom: 'Lave-linge', volume: 0.8 },
  { nom: 'Lave-linge séchant', volume: 0.9 },
  { nom: 'Sèche-linge', volume: 0.8 },
  { nom: 'Meuble de salle de bain', volume: 0.8 },
  { nom: 'Colonne de rangement', volume: 0.6 },
  { nom: 'Meuble sous-vasque', volume: 0.5 },
  { nom: 'Armoire de toilette', volume: 0.3 },
  { nom: 'Sèche-serviettes', volume: 0.2 },
  { nom: 'Étendoir à linge', volume: 0.2 },
  { nom: 'Panier à linge', volume: 0.15 },
  { nom: 'Aspirateur', volume: 0.2 },
  { nom: 'Aspirateur robot', volume: 0.05 },
  { nom: 'Aspirateur balai', volume: 0.1 },
  { nom: 'Centrale vapeur', volume: 0.1 },
  { nom: 'Planche à repasser', volume: 0.1 },

  // ─── EXTÉRIEUR / JARDIN ───
  { nom: 'Table de jardin', volume: 1.0 },
  { nom: 'Chaise de jardin', volume: 0.3 },
  { nom: 'Salon de jardin (ensemble)', volume: 2.5 },
  { nom: 'Salon de jardin en résine', volume: 2.0 },
  { nom: 'Transat / Bain de soleil', volume: 0.5 },
  { nom: 'Hamac', volume: 0.1 },
  { nom: 'Parasol', volume: 0.3 },
  { nom: "Voile d'ombrage", volume: 0.1 },
  { nom: 'Barbecue', volume: 0.6 },
  { nom: 'Barbecue à gaz (grand)', volume: 1.0 },
  { nom: 'Plancha', volume: 0.3 },
  { nom: 'Balancelle', volume: 1.5 },
  { nom: 'Bac à fleurs / Jardinière', volume: 0.3 },
  { nom: 'Pot de fleurs (grand)', volume: 0.2 },
  { nom: 'Abri de jardin (démonté)', volume: 3.0 },
  { nom: 'Serre de jardin (démontée)', volume: 2.0 },
  { nom: 'Trampoline (démonté)', volume: 1.0 },
  { nom: 'Portique de jeux', volume: 1.5 },
  { nom: 'Piscine tubulaire (démontée)', volume: 1.5 },
  { nom: 'Salon bas de jardin', volume: 1.8 },
  { nom: 'Coffre de jardin', volume: 0.6 },

  // ─── GARAGE / BRICOLAGE ───
  { nom: 'Établi', volume: 1.0 },
  { nom: 'Étagère de garage', volume: 0.8 },
  { nom: 'Armoire métallique', volume: 1.2 },
  { nom: "Servante d'atelier", volume: 0.5 },
  { nom: 'Rangement mural outils', volume: 0.3 },
  { nom: 'Tondeuse', volume: 0.5 },
  { nom: 'Tondeuse autoportée', volume: 1.5 },
  { nom: 'Taille-haie / Débroussailleuse', volume: 0.2 },
  { nom: 'Motoculteur', volume: 0.5 },
  { nom: 'Nettoyeur haute pression', volume: 0.2 },
  { nom: 'Groupe électrogène', volume: 0.3 },
  { nom: 'Compresseur', volume: 0.3 },
  { nom: 'Poste à souder', volume: 0.2 },
  { nom: 'Diable / Chariot', volume: 0.3 },
  { nom: 'Brouette', volume: 0.4 },
  { nom: 'Échelle', volume: 0.3 },
  { nom: 'Escabeau', volume: 0.2 },
  { nom: 'Échafaudage (démonté)', volume: 0.8 },
  { nom: 'Coffre de rangement extérieur', volume: 0.8 },
  { nom: 'Pneus (lot de 4)', volume: 0.4 },
  { nom: 'Coffre de toit', volume: 0.4 },

  // ─── INFORMATIQUE / HIGH-TECH ───
  { nom: 'Ordinateur de bureau (tour)', volume: 0.4 },
  { nom: "Écran d'ordinateur", volume: 0.15 },
  { nom: 'Écran PC incurvé / ultra-large', volume: 0.25 },
  { nom: 'Double écran (setup)', volume: 0.3 },
  { nom: 'Ordinateur portable', volume: 0.03 },
  { nom: 'Tablette graphique', volume: 0.02 },
  { nom: 'Imprimante', volume: 0.2 },
  { nom: 'Imprimante 3D', volume: 0.3 },
  { nom: 'Scanner', volume: 0.1 },
  { nom: 'Setup gaming (bureau + PC + périph.)', volume: 1.5 },
  { nom: 'Chaise gaming', volume: 0.6 },
  { nom: 'Console de jeu', volume: 0.05 },
  { nom: 'Console rétro / Borne', volume: 0.3 },
  { nom: 'Casque VR', volume: 0.05 },
  { nom: 'Serveur / NAS', volume: 0.2 },
  { nom: 'Onduleur', volume: 0.1 },
  { nom: 'Vidéoprojecteur', volume: 0.1 },
  { nom: 'Écran de projection', volume: 0.2 },
  { nom: 'Barre de son', volume: 0.1 },
  { nom: 'Home cinéma (enceintes + caisson)', volume: 0.6 },
  { nom: 'Enceinte colonne', volume: 0.2 },
  { nom: 'Caisson de basse', volume: 0.15 },
  { nom: 'Routeur / Box internet', volume: 0.02 },
  { nom: 'Antenne / Parabole', volume: 0.2 },

  // ─── MUSIQUE ───
  { nom: 'Piano droit', volume: 2.0 },
  { nom: 'Piano à queue', volume: 4.0 },
  { nom: 'Piano numérique / Clavier', volume: 0.4 },
  { nom: 'Guitare (avec étui)', volume: 0.2 },
  { nom: 'Guitare électrique + ampli', volume: 0.4 },
  { nom: 'Basse', volume: 0.2 },
  { nom: 'Batterie (kit complet)', volume: 1.5 },
  { nom: 'Batterie électronique', volume: 0.8 },
  { nom: 'Ampli', volume: 0.2 },
  { nom: 'Ampli guitare (grand)', volume: 0.4 },
  { nom: 'Platine vinyle', volume: 0.1 },
  { nom: 'Synthétiseur', volume: 0.2 },
  { nom: 'Orgue', volume: 1.0 },
  { nom: 'Violon / Alto (étui)', volume: 0.05 },
  { nom: 'Violoncelle (étui)', volume: 0.3 },
  { nom: 'Contrebasse', volume: 0.8 },
  { nom: 'Saxophone / Cuivre (étui)', volume: 0.1 },
  { nom: 'Flûte / Clarinette (étui)', volume: 0.03 },
  { nom: 'Harpe', volume: 1.0 },
  { nom: 'Accordéon', volume: 0.15 },
  { nom: 'Table de mixage / Matériel DJ', volume: 0.2 },
  { nom: 'Pupitre à musique', volume: 0.05 },

  // ─── SPORT / FITNESS ───
  { nom: 'Vélo', volume: 1.0 },
  { nom: 'Vélo enfant', volume: 0.5 },
  { nom: 'Vélo électrique', volume: 1.0 },
  { nom: 'Vélo cargo', volume: 1.5 },
  { nom: "Vélo d'appartement / Home-trainer", volume: 0.8 },
  { nom: 'Tapis de course', volume: 1.2 },
  { nom: 'Vélo elliptique', volume: 1.0 },
  { nom: 'Rameur', volume: 0.8 },
  { nom: 'Stepper', volume: 0.3 },
  { nom: 'Banc de musculation', volume: 1.0 },
  { nom: 'Rack / Cage de musculation', volume: 2.0 },
  { nom: 'Haltères / Poids (lot)', volume: 0.3 },
  { nom: 'Barre de traction', volume: 0.1 },
  { nom: 'Tapis de yoga / gym', volume: 0.05 },
  { nom: 'Trottinette', volume: 0.2 },
  { nom: 'Trottinette électrique', volume: 0.15 },
  { nom: 'Skis / Snowboard', volume: 0.2 },
  { nom: 'Planche de surf', volume: 0.3 },
  { nom: 'Paddle / Kayak', volume: 0.8 },
  { nom: 'Canoë', volume: 1.2 },
  { nom: 'Table de ping-pong', volume: 1.5 },
  { nom: 'Baby-foot', volume: 1.2 },
  { nom: 'Billard', volume: 2.5 },
  { nom: 'Table de air hockey', volume: 1.2 },
  { nom: 'Fléchettes / Cible', volume: 0.05 },
  { nom: 'Punching-ball / Sac de frappe', volume: 0.4 },
  { nom: 'Skateboard', volume: 0.05 },

  // ─── LOISIRS / HOBBIES ───
  { nom: 'Machine à coudre', volume: 0.15 },
  { nom: 'Surjeteuse', volume: 0.15 },
  { nom: 'Métier à tisser', volume: 0.5 },
  { nom: 'Chevalet de peinture', volume: 0.3 },
  { nom: 'Établi loisirs créatifs', volume: 0.8 },
  { nom: 'Four à céramique / poterie', volume: 0.5 },
  { nom: 'Tour de potier', volume: 0.4 },
  { nom: 'Aquarium (vide)', volume: 0.3 },
  { nom: 'Grand aquarium + meuble', volume: 1.0 },
  { nom: 'Terrarium / Vivarium', volume: 0.3 },
  { nom: 'Cage / Habitat animal', volume: 0.4 },
  { nom: 'Niche pour chien', volume: 0.5 },
  { nom: 'Arbre à chat', volume: 0.4 },
  { nom: 'Clapier / Poulailler', volume: 0.8 },
  { nom: 'Matériel photo (studio)', volume: 0.3 },
  { nom: 'Télescope', volume: 0.2 },
  { nom: 'Maquette / Circuit (grand)', volume: 0.5 },
  { nom: 'Table de jeu / Poker', volume: 0.8 },
  { nom: "Borne d'arcade", volume: 1.0 },
  { nom: 'Flipper', volume: 1.2 },
  { nom: 'Machine à sous / Jukebox', volume: 1.0 },

  // ─── ENFANTS / BÉBÉ ───
  { nom: 'Poussette', volume: 0.4 },
  { nom: 'Poussette double', volume: 0.6 },
  { nom: 'Parc / Lit parapluie bébé', volume: 0.3 },
  { nom: 'Chaise haute', volume: 0.3 },
  { nom: 'Transat bébé', volume: 0.2 },
  { nom: 'Trotteur / Youpala', volume: 0.2 },
  { nom: 'Balancelle bébé', volume: 0.3 },
  { nom: 'Coffre à jouets', volume: 0.4 },
  { nom: 'Toboggan / Structure de jeu', volume: 0.8 },
  { nom: 'Maison de jardin enfant', volume: 1.5 },
  { nom: 'Voiture électrique enfant', volume: 0.6 },
  { nom: 'Kart à pédales', volume: 0.4 },

  // ─── DIVERS ───
  { nom: 'Carton petit', volume: 0.05 },
  { nom: 'Carton moyen', volume: 0.1 },
  { nom: 'Carton grand', volume: 0.2 },
  { nom: 'Plante (grande, en pot)', volume: 0.5 },
  { nom: 'Plante (très grande / arbuste)', volume: 1.0 },
  { nom: 'Valise', volume: 0.15 },
  { nom: 'Grande valise / soute', volume: 0.25 },
  { nom: 'Malle de rangement', volume: 0.3 },
  { nom: 'Statue / Sculpture', volume: 0.3 },
  { nom: 'Tableau / Cadre (grand)', volume: 0.15 },
  { nom: 'Tableau / Cadre (très grand)', volume: 0.3 },
  { nom: 'Tapis roulé (grand)', volume: 0.4 },
  { nom: 'Portant à vêtements', volume: 0.3 },
  { nom: 'Fauteuil roulant', volume: 0.5 },
  { nom: "Distributeur d'eau / Fontaine", volume: 0.3 },
  { nom: 'Objet personnalisé', volume: 0 },
];

export const OBJETS_A_EMBALLER = [
  // ─── CUISINE / VAISSELLE ───
  { nom: 'Assiette', volume: 0.0025, carton: 'petit' },
  { nom: 'Assiette creuse', volume: 0.0025, carton: 'petit' },
  { nom: 'Assiette à dessert', volume: 0.0015, carton: 'petit' },
  { nom: 'Bol / Saladier', volume: 0.003, carton: 'petit' },
  { nom: 'Ramequin', volume: 0.0008, carton: 'petit' },
  { nom: 'Verre', volume: 0.0008, carton: 'petit' },
  { nom: 'Verre à pied / Flûte', volume: 0.001, carton: 'petit' },
  { nom: 'Tasse / Mug', volume: 0.0012, carton: 'petit' },
  { nom: 'Couverts (lot de 6)', volume: 0.0015, carton: 'petit' },
  { nom: 'Couteaux de cuisine (bloc)', volume: 0.003, carton: 'petit' },
  { nom: 'Bouteille (vin, alcool)', volume: 0.0015, carton: 'petit' },
  { nom: 'Carafe / Pichet', volume: 0.002, carton: 'petit' },
  { nom: 'Conserve / Bocal', volume: 0.0008, carton: 'petit' },
  { nom: 'Théière / Cafetière verre', volume: 0.003, carton: 'petit' },
  { nom: 'Plat de service', volume: 0.004, carton: 'petit' },
  { nom: 'Moule à gâteau', volume: 0.003, carton: 'petit' },
  { nom: 'Casserole', volume: 0.008, carton: 'standard' },
  { nom: 'Poêle', volume: 0.006, carton: 'standard' },
  { nom: 'Wok', volume: 0.008, carton: 'standard' },
  { nom: 'Cocotte / Faitout', volume: 0.012, carton: 'standard' },
  { nom: 'Petit électroménager (grille-pain, mixeur...)', volume: 0.015, carton: 'standard' },
  { nom: 'Cafetière / Bouilloire', volume: 0.01, carton: 'standard' },
  { nom: 'Machine à café à grains', volume: 0.025, carton: 'standard' },
  { nom: 'Robot pâtissier', volume: 0.02, carton: 'standard' },
  { nom: 'Blender / Mixeur plongeant', volume: 0.008, carton: 'standard' },
  { nom: 'Friteuse / Airfryer', volume: 0.015, carton: 'standard' },
  { nom: 'Multicuiseur / Cookeo', volume: 0.02, carton: 'standard' },
  { nom: 'Ustensiles de cuisine (lot)', volume: 0.005, carton: 'standard' },
  { nom: 'Tupperware / Boîtes (lot)', volume: 0.01, carton: 'standard' },
  { nom: 'Épices / Condiments (lot)', volume: 0.004, carton: 'petit' },
  { nom: 'Torchons / Maniques (lot)', volume: 0.003, carton: 'standard' },

  // ─── MÉDIA / HIGH-TECH (à emballer) ───
  { nom: 'Petite enceinte / Bluetooth', volume: 0.002, carton: 'standard' },
  { nom: 'Enceinte connectée (Alexa, Google...)', volume: 0.002, carton: 'standard' },
  { nom: 'Casque audio', volume: 0.003, carton: 'standard' },
  { nom: 'Écouteurs / Earbuds', volume: 0.0005, carton: 'petit' },
  { nom: 'Micro / Matériel podcast', volume: 0.003, carton: 'standard' },
  { nom: 'Webcam', volume: 0.0008, carton: 'petit' },
  { nom: 'Disque dur externe', volume: 0.0005, carton: 'petit' },
  { nom: 'Clé USB / Carte mémoire (lot)', volume: 0.0002, carton: 'petit' },
  { nom: 'Manette / Périphérique de jeu', volume: 0.003, carton: 'standard' },
  { nom: 'Volant / Joystick gaming', volume: 0.008, carton: 'standard' },
  { nom: 'Tablette', volume: 0.001, carton: 'petit' },
  { nom: 'Liseuse', volume: 0.0005, carton: 'petit' },
  { nom: 'Appareil photo (avec objectifs)', volume: 0.006, carton: 'standard' },
  { nom: 'Caméra / GoPro', volume: 0.001, carton: 'petit' },
  { nom: 'Drone', volume: 0.008, carton: 'standard' },
  { nom: 'Trépied', volume: 0.006, carton: 'standard' },
  { nom: 'Câbles / Chargeurs (lot)', volume: 0.003, carton: 'standard' },
  { nom: 'Clavier / Souris', volume: 0.004, carton: 'standard' },
  { nom: 'Petit appareil électronique', volume: 0.005, carton: 'standard' },
  { nom: 'Multiprises / Rallonges (lot)', volume: 0.004, carton: 'standard' },
  { nom: 'Décodeur / Box TV', volume: 0.002, carton: 'petit' },
  { nom: 'Ampli casque / DAC', volume: 0.002, carton: 'standard' },

  // ─── SALON / BUREAU / MÉDIAS ───
  { nom: 'Livre', volume: 0.0015, carton: 'petit' },
  { nom: 'Livre relié / Beau livre', volume: 0.003, carton: 'petit' },
  { nom: 'Magazine / BD', volume: 0.001, carton: 'petit' },
  { nom: 'Manga / Comics', volume: 0.0008, carton: 'petit' },
  { nom: 'Classeur / Dossier', volume: 0.004, carton: 'petit' },
  { nom: 'DVD / Blu-ray', volume: 0.0004, carton: 'petit' },
  { nom: 'CD (boîtier)', volume: 0.0003, carton: 'petit' },
  { nom: 'Jeu vidéo (boîtier)', volume: 0.0004, carton: 'petit' },
  { nom: 'Vinyle (disque)', volume: 0.001, carton: 'petit' },
  { nom: 'Cassette / VHS', volume: 0.0006, carton: 'petit' },
  { nom: 'Cadre photo', volume: 0.002, carton: 'petit' },
  { nom: 'Poster / Affiche (roulé)', volume: 0.002, carton: 'petit' },
  { nom: 'Vase', volume: 0.005, carton: 'petit' },
  { nom: 'Bibelot / Objet déco', volume: 0.004, carton: 'standard' },
  { nom: 'Statuette déco', volume: 0.005, carton: 'standard' },
  { nom: 'Figurine de collection', volume: 0.002, carton: 'standard' },
  { nom: 'Bougeoir / Photophore', volume: 0.003, carton: 'standard' },
  { nom: 'Bougie / Diffuseur', volume: 0.002, carton: 'standard' },
  { nom: 'Horloge murale', volume: 0.004, carton: 'standard' },
  { nom: 'Jeux de société (boîte)', volume: 0.006, carton: 'standard' },
  { nom: 'Cartes / Petits jeux (lot)', volume: 0.002, carton: 'petit' },
  { nom: 'Puzzle (boîte)', volume: 0.004, carton: 'standard' },
  { nom: 'Abat-jour', volume: 0.02, carton: 'grand' },
  { nom: 'Plaid / Coussins déco (lot)', volume: 0.015, carton: 'grand' },
  { nom: 'Plante artificielle', volume: 0.01, carton: 'grand' },

  // ─── CHAMBRE / DRESSING / TEXTILE ───
  { nom: 'Vêtement plié (t-shirt, pantalon...)', volume: 0.002, carton: 'grand' },
  { nom: 'Pull / Gilet épais', volume: 0.004, carton: 'grand' },
  { nom: 'Manteau / Veste', volume: 0.008, carton: 'grand' },
  { nom: 'Sous-vêtements / Chaussettes (lot)', volume: 0.002, carton: 'grand' },
  { nom: 'Écharpe / Bonnet / Gants (lot)', volume: 0.003, carton: 'grand' },
  { nom: 'Chaussures (paire)', volume: 0.006, carton: 'standard' },
  { nom: 'Bottes (paire)', volume: 0.01, carton: 'standard' },
  { nom: 'Sac à main', volume: 0.008, carton: 'standard' },
  { nom: 'Ceinture / Accessoires (lot)', volume: 0.002, carton: 'standard' },
  { nom: 'Bijoux / Montres (boîte)', volume: 0.002, carton: 'petit' },
  { nom: 'Chapeau', volume: 0.008, carton: 'grand' },
  { nom: 'Drap / Housse de couette', volume: 0.006, carton: 'grand' },
  { nom: 'Couverture / Plaid', volume: 0.012, carton: 'grand' },
  { nom: 'Couette', volume: 0.04, carton: 'grand' },
  { nom: 'Oreiller', volume: 0.015, carton: 'grand' },
  { nom: 'Coussin', volume: 0.01, carton: 'grand' },
  { nom: 'Vêtement sur cintre (chemise, robe...)', volume: 0.008, carton: 'penderie' },
  { nom: 'Costume / Tailleur', volume: 0.015, carton: 'penderie' },
  { nom: 'Manteau long sur cintre', volume: 0.02, carton: 'penderie' },
  { nom: 'Robe de soirée / Mariée', volume: 0.03, carton: 'penderie' },

  // ─── SALLE DE BAIN ───
  { nom: 'Produit de salle de bain', volume: 0.0015, carton: 'standard' },
  { nom: 'Serviette de bain', volume: 0.005, carton: 'grand' },
  { nom: 'Drap de bain', volume: 0.008, carton: 'grand' },
  { nom: 'Trousse de toilette', volume: 0.003, carton: 'standard' },
  { nom: 'Sèche-cheveux / Lisseur', volume: 0.003, carton: 'standard' },
  { nom: 'Tapis de bain', volume: 0.004, carton: 'grand' },
  { nom: 'Balance', volume: 0.003, carton: 'standard' },

  // ─── ENFANTS ───
  { nom: 'Jouet', volume: 0.006, carton: 'standard' },
  { nom: 'Peluche', volume: 0.008, carton: 'standard' },
  { nom: 'Grande peluche', volume: 0.03, carton: 'grand' },
  { nom: 'Puzzle / Jeu de construction (boîte)', volume: 0.005, carton: 'standard' },
  { nom: 'Lego (grande boîte)', volume: 0.015, carton: 'standard' },
  { nom: 'Livre enfant', volume: 0.002, carton: 'petit' },
  { nom: 'Vêtements enfant (lot)', volume: 0.003, carton: 'grand' },
  { nom: 'Biberons / Matériel bébé (lot)', volume: 0.004, carton: 'standard' },
  { nom: 'Jeux de bain (lot)', volume: 0.005, carton: 'standard' },

  // ─── DIVERS ───
  { nom: 'Outil à main (marteau, tournevis...)', volume: 0.001, carton: 'petit' },
  { nom: 'Boîte à outils', volume: 0.015, carton: 'standard' },
  { nom: 'Perceuse / Visseuse', volume: 0.006, carton: 'standard' },
  { nom: 'Visserie / Quincaillerie (lot)', volume: 0.002, carton: 'petit' },
  { nom: 'Boîte de rangement', volume: 0.02, carton: 'standard' },
  { nom: 'Plante (petite, en pot)', volume: 0.01, carton: 'standard' },
  { nom: 'Rideau', volume: 0.008, carton: 'grand' },
  { nom: 'Voilage', volume: 0.005, carton: 'grand' },
  { nom: 'Nappe / Linge de table', volume: 0.003, carton: 'grand' },
  { nom: 'Sac de sport', volume: 0.02, carton: 'grand' },
  { nom: 'Matériel de camping (sac)', volume: 0.03, carton: 'grand' },
  { nom: 'Tente (sac)', volume: 0.025, carton: 'grand' },
  { nom: 'Sac de couchage', volume: 0.015, carton: 'grand' },
  { nom: 'Décoration de Noël (boîte)', volume: 0.02, carton: 'standard' },
  { nom: 'Guirlandes / Déco (lot)', volume: 0.01, carton: 'standard' },
  { nom: 'Documents / Archives (lot)', volume: 0.005, carton: 'petit' },
  { nom: "Produits d'entretien (lot)", volume: 0.008, carton: 'standard' },
  { nom: 'Trousse de secours / Médicaments', volume: 0.002, carton: 'petit' },
  { nom: 'Parapluie', volume: 0.002, carton: 'standard' },
  { nom: 'Gamelle / Accessoires animaux (lot)', volume: 0.005, carton: 'standard' },
  { nom: 'Litière / Sac de croquettes', volume: 0.015, carton: 'standard' },
  { nom: 'Fer à repasser', volume: 0.002, carton: 'standard' },
  { nom: 'Set de table / Dessous de plat (lot)', volume: 0.002, carton: 'petit' },
  { nom: 'Corbeille / Panier de rangement', volume: 0.008, carton: 'standard' },
  { nom: 'Poubelle', volume: 0.015, carton: 'grand' },
  { nom: 'Balai / Serpillière / Pelle', volume: 0.005, carton: 'grand' },
  { nom: 'Seau / Bassine', volume: 0.008, carton: 'standard' },
  { nom: 'Cintres (lot)', volume: 0.004, carton: 'standard' },
  { nom: 'Housse de rangement sous vide', volume: 0.005, carton: 'grand' },
  { nom: 'Réveil / Petite horloge', volume: 0.001, carton: 'petit' },
  { nom: 'Lampe de chevet', volume: 0.004, carton: 'standard' },
  { nom: 'Lampe de bureau', volume: 0.004, carton: 'standard' },
  { nom: 'Radio / Poste', volume: 0.003, carton: 'standard' },
  { nom: 'Album photo', volume: 0.002, carton: 'petit' },
  { nom: 'Fournitures de bureau (lot)', volume: 0.005, carton: 'standard' },
  { nom: 'Papeterie / Cahiers (lot)', volume: 0.004, carton: 'petit' },
  { nom: 'Sac à dos', volume: 0.008, carton: 'standard' },
  { nom: 'Matériel scolaire enfant (lot)', volume: 0.005, carton: 'standard' },
  { nom: 'Serviettes de plage (lot)', volume: 0.008, carton: 'grand' },
  { nom: 'Coussin de sol / Tapis de jeu', volume: 0.02, carton: 'grand' },
];
